package com.davidsalas.tenpochallenge.application.config;

public enum ErrorCode {
    PERCENTAGE_ENTITY_NOT_FOUND,
    LAST_CALCULATION_NOT_FOUND,
    PERCENTAGE_ENTITY_BAD_REQUEST,
    PERCENTAGE_REPOSITORY_CONFLICT,
    REPOSITORY_NOT_AVAILABLE,
    METHOD_ARGUMENT_MISMATCH,
    METHOD_ARGUMENT_NOT_VALID,
    UNEXPECTED_ERROR
}
